import Head from 'next/head';

const About = () => {
  return (
    <>
      <Head>
        <title>Dhemeira | About</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        <h1 className="text-3xl font-bold">About</h1>
      </div>
    </>
  );
};

export default About;
